spring:
  application:
    name:
      todo
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
