### POST リクエストの例：Todo を作成する場合
GET http://localhost:8080/api/v1/todos

###
@id = 5546bc1c-a65e-4053-a806-d05c1449cc39
GET http://localhost:8080/api/v1/todos/{{id}}

###
POST http://localhost:8080/api/v1/todos
Content-Type: application/json

{
    "title": "New Todo1",
    "status": "NOT_STARTED"
}

###
@id = 97c637c0-2a63-4cc8-8fe4-b4e6c0bb6642
DELETE  http://localhost:8080/api/v1/todos/{{id}}